using Descope.Mgmt;
using Descope.Mgmt.Scim;
using Descope.Mgmt.V1;
using Descope.Mgmt.V2;

namespace Descope;

/// <summary>
/// Wrapper implementation of the Descope Management Client that delegates to the generated client.
/// This class will NOT be regenerated by Kiota and provides a stable interface for dependency injection.
/// </summary>
internal class DescopeManagementClient : IDescopeManagementClient
{
    private readonly DescopeMgmtKiotaClient _innerClient;

    /// <summary>
    /// Initializes a new instance of the DescopeManagementClient wrapper.
    /// </summary>
    /// <param name="innerClient">The generated Kiota client to wrap.</param>
    public DescopeManagementClient(DescopeMgmtKiotaClient innerClient)
    {
        _innerClient = innerClient ?? throw new ArgumentNullException(nameof(innerClient));
    }

    /// <inheritdoc/>
    public ScimRequestBuilder Scim => _innerClient.Scim;

    /// <inheritdoc/>
    public V1RequestBuilder V1 => _innerClient.V1;

    /// <inheritdoc/>
    public V2RequestBuilder V2 => _innerClient.V2;
}
