using Descope.Mgmt;
using Descope.Auth;

namespace Descope;

/// <summary>
/// Wrapper implementation of the Descope Client that delegates to the generated clients.
/// This class will NOT be regenerated by Kiota and provides a stable interface for dependency injection.
/// </summary>
public class DescopeClient : IDescopeClient
{
    private readonly DescopeMgmtClient _mgmtClient;
    private readonly DescopeAuthClient _authClient;

    /// <summary>
    /// Initializes a new instance of the DescopeClient wrapper.
    /// </summary>
    /// <param name="mgmtKiotaClient">The generated Management Kiota client to wrap.</param>
    /// <param name="authKiotaClient">The generated Auth Kiota client to wrap.</param>
    public DescopeClient(DescopeMgmtKiotaClient mgmtKiotaClient, DescopeAuthKiotaClient authKiotaClient)
    {
        _mgmtClient = new DescopeMgmtClient(mgmtKiotaClient ?? throw new ArgumentNullException(nameof(mgmtKiotaClient)));
        _authClient = new DescopeAuthClient(authKiotaClient ?? throw new ArgumentNullException(nameof(authKiotaClient)));
    }

    public class DescopeMgmtClient
    {
        private readonly DescopeMgmtKiotaClient _mgmtKiotaClient;

        internal DescopeMgmtClient(DescopeMgmtKiotaClient mgmtKiotaClient)
        {
            _mgmtKiotaClient = mgmtKiotaClient;
        }

        public Mgmt.V1.Mgmt.MgmtRequestBuilder V1 => _mgmtKiotaClient.V1.Mgmt;
        public Mgmt.V2.Mgmt.MgmtRequestBuilder V2 => _mgmtKiotaClient.V2.Mgmt;
    }

    public class DescopeAuthClient
    {
        private readonly DescopeAuthKiotaClient _authKiotaClient;

        internal DescopeAuthClient(DescopeAuthKiotaClient authKiotaClient)
        {
            _authKiotaClient = authKiotaClient;
        }

        public Auth.V1.Auth.AuthRequestBuilder V1 => _authKiotaClient.V1.Auth;
    }

    /// <inheritdoc/>
    public DescopeMgmtClient Mgmt => _mgmtClient;

    /// <inheritdoc/>
    public DescopeAuthClient Auth => _authClient;
}
